---
compositions:
  order:
    terraform:
      - account
      - vpc
      - cluster

# Kompos configuration for versioned sources example
terraform:
  version: "v1.12.2" 
  versioned_module_sources: true  # Enable versioned module source processing
  local_path: "./compositions/terraform"
  root_path: ""


