---
komposconfig:
  terraform:
    local_path: "./compositions/terraform"
  
  compositions:
    order:
      terraform:
        - account
        - network
        - cluster
      helmfile:
        - helmfiles
    
    # System/metadata keys to exclude from generated outputs
    system_keys:
      terraform:
        - provider
        - terraform
      tfe:
        - workspaces
        - composition
        - tfe
